/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2022 Northeastern University
 * Copyright (c) 2022 Sapienza, University of Rome
 * Copyright (c) 2022 University of Padova
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Andrea Lacava <thecave003@gmail.com>
 *		   Tommaso Zugno <tommasozugno@gmail.com>
 *		   Michele Polese <michele.polese@gmail.com>
 */

#include <ns3/oran-interface.h>
#include <ns3/asn1c-types.h>

#include <ns3/log.h>
#include <thread>
#include <mutex>
#include <unordered_map>
#include "encode_e2apv1.hpp"

extern "C" {
  #include "RICsubscriptionRequest.h"
  #include "RICactionType.h"
  #include "ProtocolIE-Field.h"
  #include "InitiatingMessage.h"
}

/* =========================================================================
 * Global trampoline dispatch table.
 *
 * v3 e2sim stores raw SubscriptionCallback (void(*)(E2AP_PDU_t*)) pointers and
 * calls them directly.  To support std::bind / lambda callers (mmwave/lte net-
 * device files) we keep a global map of E2TermCallback (std::function) objects
 * keyed by ranFunctionId, protected by a mutex, and register a single static
 * trampoline per slot that dispatches through the map.
 *
 * Limitation: only one E2Termination instance per RAN-function-ID is supported
 * (single-node scenario-zero topology; this is a 1-gNB simulation).
 * ========================================================================= */
namespace {

std::mutex                                   g_cbMtx;
std::unordered_map<long, E2TermCallback>     g_cbMap;

/* Each registered function ID gets its own trampoline generated by
 * MakeTrampoline().  We pre-generate trampolines for the IDs used in
 * scenario-zero: 2 = KPM (L-release: kpimon-go hardcodes RANfunctionID 2,
 * see ric-app-kpimon-go control/control.go:45), 200 = KPM (Bronze legacy),
 * 300 = RC/Sm, plus a generic fallback.                                    */
static void Trampoline2 (E2AP_PDU_t *pdu) {
  std::lock_guard<std::mutex> lk (g_cbMtx);
  auto it = g_cbMap.find (2);
  if (it != g_cbMap.end () && it->second) it->second (pdu);
}
static void Trampoline200 (E2AP_PDU_t *pdu) {
  std::lock_guard<std::mutex> lk (g_cbMtx);
  auto it = g_cbMap.find (200);
  if (it != g_cbMap.end () && it->second) it->second (pdu);
}
static void Trampoline300 (E2AP_PDU_t *pdu) {
  std::lock_guard<std::mutex> lk (g_cbMtx);
  auto it = g_cbMap.find (300);
  if (it != g_cbMap.end () && it->second) it->second (pdu);
}
static void TrampolineFallback (E2AP_PDU_t * /*pdu*/) {
  /* no-op for unregistered function IDs */
}

static SubscriptionCallback
GetTrampoline (long funcId)
{
  switch (funcId)
    {
    case 2:   return Trampoline2;
    case 200: return Trampoline200;
    case 300: return Trampoline300;
    default:  return TrampolineFallback;
    }
}

} // anonymous namespace

namespace ns3 {

NS_LOG_COMPONENT_DEFINE ("E2Termination");

NS_OBJECT_ENSURE_REGISTERED (E2Termination);

TypeId E2Termination::GetTypeId ()
{
  static TypeId tid = TypeId ("ns3::E2Termination")
    .SetParent<Object>()
    .AddConstructor<E2Termination>();
  return tid;
}

E2Termination::E2Termination ()
{
  NS_FATAL_ERROR("Do not use the default constructor");
}

E2Termination::E2Termination(const std::string ricAddress, 
                  const uint16_t ricPort,
                  const uint16_t clientPort,
                  const std::string gnbId,
                  const std::string plmnId)
  : m_ricAddress (ricAddress),
    m_ricPort (ricPort),
    m_clientPort (clientPort),
    m_gnbId (gnbId),
    m_plmnId(plmnId)
{
  NS_LOG_FUNCTION (this);
  m_e2sim = new E2Sim;
  
  // create a new file which will be used to trace the encoded messages
  // TODO create an appropriate log class to handle these messages
  // FILE* f = fopen ("messages.txt", "w");
  // fclose (f);
}

void
E2Termination::RegisterFunctionDescToE2Sm (long ranFunctionId, Ptr<FunctionDescription> ranFunctionDescription)
{
  // create an octet string and copy the e2smbuffer
  OCTET_STRING_t *rfdBuf = (OCTET_STRING_t *) calloc (1, sizeof (OCTET_STRING_t));
  rfdBuf->buf = (uint8_t *) calloc (1, ranFunctionDescription->m_size);
  rfdBuf->size = ranFunctionDescription->m_size;
  memcpy (rfdBuf->buf, ranFunctionDescription->m_buffer, ranFunctionDescription->m_size);

  m_e2sim->register_e2sm (ranFunctionId, rfdBuf);
}

void
E2Termination::StoreAndRegisterCallback (long ranFunctionId, E2TermCallback cb)
{
  /* Store the std::function so the trampoline can call it. */
  {
    std::lock_guard<std::mutex> lk (g_cbMtx);
    g_cbMap[ranFunctionId] = std::move (cb);
  }
  /* Only funcIds with a pre-generated trampoline (2=KPM L-release, 200=KPM
   * Bronze legacy, 300=RC) are dispatchable; any other id registers the no-op
   * fallback, so its callback would NEVER fire (indications silently stop).
   * Warn loudly — if the live RIC pins KPM to a different funcId, add a
   * TrampolineN + GetTrampoline case. (Phase-7 live run: ns-3 now registers KPM
   * under 2 to match kpimon-go's hardcoded RANfunctionID — reconciled.) */
  if (ranFunctionId != 2 && ranFunctionId != 200 && ranFunctionId != 300)
    {
      NS_LOG_WARN ("RegisterCallback: no trampoline for RAN function ID "
                   << ranFunctionId << " — its subscription callback will NOT "
                      "fire (no-op fallback registered). Add a trampoline case.");
    }
  /* Register the static trampoline (raw function pointer) with e2sim. */
  m_e2sim->register_subscription_callback (ranFunctionId, GetTrampoline (ranFunctionId));
}

void
E2Termination::RegisterKpmCallbackToE2Sm (long ranFunctionId,
                                          Ptr<FunctionDescription> ranFunctionDescription,
                                          E2TermCallback sbCb)
{
  RegisterFunctionDescToE2Sm (ranFunctionId, ranFunctionDescription);
  StoreAndRegisterCallback (ranFunctionId, std::move (sbCb));
}

void
E2Termination::RegisterSmCallbackToE2Sm (long ranFunctionId,
                                         Ptr<FunctionDescription> ranFunctionDescription,
                                         SmCallback smCb)
{
  /* E2SM-RC control path excluded from build; register slot for ABI completeness. */
  RegisterFunctionDescToE2Sm (ranFunctionId, ranFunctionDescription);
  StoreAndRegisterCallback (ranFunctionId, std::move (smCb));
}

void E2Termination::Start ()
{
  NS_LOG_FUNCTION (this);

  NS_ABORT_MSG_IF(m_ricAddress.empty(), "Set the RIC information first");
  
  // create a thread to host e2sim execution
  std::thread e2simThread (&E2Termination::DoStart, this);
  e2simThread.detach ();
}

void E2Termination::DoStart ()
{
  NS_LOG_FUNCTION (this);

  NS_LOG_INFO ("In ns3::E2Term:  GNB" << m_gnbId << ", clientPort " << m_clientPort << ", ricPort "
                                 << m_ricPort <<  ", PlmnID "
                                 << m_plmnId);

  // L-release adapter: the vendored OSC libe2sim exposes run_loop(int argc, char** argv)
  // (oran-e2sim/e2sim/src/base/e2sim.cpp), NOT the wineslab 5-arg overload. Its
  // read_input_options() (e2sim_defs.cpp) reads ONLY argv[1]=server-ip and argv[2]=server-port
  // when argc==3, and exit(1)s for argc>3. The gNB identity (gnbId/plmnId) comes from the
  // registered RAN-function descriptor. Only the RIC address/port go via argv.
  // Mirrors examples/e2-setup-minimal.cc.
  //
  // SCTP source port: the OSC e2sim hardcodes RIC_SCTP_SRC_PORT (36422) for the client
  // bind. scenario-zero embeds one E2 agent per gNB in a single process, so they MUST bind
  // distinct source ports — else the (src,dst) 4-tuple collides and the 2nd+ connect() fails
  // with EADDRNOTAVAIL (then e2sim exit(1)s, aborting the run). m_clientPort is unique per
  // gNB (mmwave-helper: m_e2localPort + cellId); push it into e2sim's client bind.
  m_e2sim->set_client_src_port (m_clientPort);
  //
  // run_loop() blocks for the lifetime of this detached thread, so these locals stay alive
  // for as long as run_loop() reads them.
  std::string ricPortStr = std::to_string (m_ricPort);
  char* argv[] = {
      const_cast<char*> ("ns3-e2term"),       // argv[0] program name (unused by parser)
      const_cast<char*> (m_ricAddress.c_str ()), // argv[1] RIC E2Term IP
      const_cast<char*> (ricPortStr.c_str ()),   // argv[2] RIC E2Term SCTP port
      nullptr};
  int argc = 3;

  m_e2sim->run_loop (argc, argv);
}

E2Termination::~E2Termination ()
{
  NS_LOG_FUNCTION (this);
  delete m_e2sim;
}

E2Termination::RicSubscriptionRequest_rval_s 
E2Termination::ProcessRicSubscriptionRequest (E2AP_PDU_t* sub_req_pdu)
{
  //Record RIC Request ID
  //Go through RIC action to be Setup List
  //Find first entry with REPORT action Type
  //Record ricActionID
  //Encode subscription response

  RICsubscriptionRequest_t orig_req = sub_req_pdu->choice.initiatingMessage->value.choice.RICsubscriptionRequest;

  // RICsubscriptionResponse_IEs_t *ricreqid = (RICsubscriptionResponse_IEs_t*)calloc(1, sizeof(RICsubscriptionResponse_IEs_t));
           
  int count = orig_req.protocolIEs.list.count;
  int size = orig_req.protocolIEs.list.size;

  RICsubscriptionRequest_IEs_t **ies = (RICsubscriptionRequest_IEs_t**)orig_req.protocolIEs.list.array;

  NS_LOG_DEBUG ("Number of IEs " << count);
  NS_LOG_DEBUG ("Size of IEs " << size);

  RICsubscriptionRequest_IEs__value_PR pres;
  
  uint16_t reqRequestorId {};
  uint16_t reqInstanceId {};
  uint16_t ranFuncionId {};
  uint8_t reqActionId {};
  
  std::vector<long> actionIdsAccept;
  std::vector<long> actionIdsReject;
  
  // iterate over the IEs
  for (int i = 0; i < count; i++) 
  {
    RICsubscriptionRequest_IEs_t *next_ie = ies[i];
    pres = next_ie->value.present; // value of the current IE
      
    switch(pres) 
    {
      // IE containing the RIC Request ID
      case RICsubscriptionRequest_IEs__value_PR_RICrequestID:
        {
          NS_LOG_DEBUG ("Processing RIC Request ID field");	
          RICrequestID_t reqId = next_ie->value.choice.RICrequestID;
          reqRequestorId = reqId.ricRequestorID;
          reqInstanceId = reqId.ricInstanceID;
          NS_LOG_DEBUG ( "RIC Requestor ID " << reqRequestorId);
          NS_LOG_DEBUG ( "RIC Instance ID " << reqInstanceId);
          break;
        }
      // IE containing the RAN Function ID
      case RICsubscriptionRequest_IEs__value_PR_RANfunctionID:
        {
          NS_LOG_DEBUG ("Processing RAN Function ID field");	
          ranFuncionId = next_ie->value.choice.RANfunctionID;
          NS_LOG_DEBUG ("RAN Function ID " << ranFuncionId);
          break;
        }
      case RICsubscriptionRequest_IEs__value_PR_RICsubscriptionDetails:
        {
          NS_LOG_DEBUG ("Processing RIC Subscription Details field");
          RICsubscriptionDetails_t subDetails = next_ie->value.choice.RICsubscriptionDetails;
          
          // RIC Event Trigger Definition
          RICeventTriggerDefinition_t triggerDef = subDetails.ricEventTriggerDefinition;

          // TODO How to decode this field?
          uint8_t size = 20;  
          uint8_t *buf = (uint8_t *)calloc(1,size);
          memcpy(buf, &triggerDef, size);
          NS_LOG_DEBUG ("RIC Event Trigger Definition " << std::to_string (*buf));
                    
          // Sequence of actions
          RICactions_ToBeSetup_List_t actionList = subDetails.ricAction_ToBeSetup_List;
          // TODO We are ignoring the trigger definition
  
          int actionCount = actionList.list.count;
          NS_LOG_DEBUG ("Number of actions " << actionCount);
  
          auto **item_array = actionList.list.array;
          bool foundAction = false;
  
          for (int i = 0; i < actionCount; i++) 
          {
            auto *next_item = item_array[i];
            RICactionID_t actionId = ((RICaction_ToBeSetup_ItemIEs*)next_item)->value.choice.RICaction_ToBeSetup_Item.ricActionID;
            RICactionType_t actionType = ((RICaction_ToBeSetup_ItemIEs*)next_item)->value.choice.RICaction_ToBeSetup_Item.ricActionType;
                        
            //We identify the first action whose type is REPORT
            //That is the only one accepted; all others are rejected
            if (!foundAction && (actionType == RICactionType_report || actionType == RICactionType_insert))
            {
              reqActionId = actionId;
              actionIdsAccept.push_back(reqActionId);
              NS_LOG_DEBUG ("Action ID " << actionId << " accepted");
              foundAction = true;
            } 
            else 
            {
              reqActionId = actionId;
              NS_LOG_DEBUG ("Action ID " << actionId << " rejected");
              // actionIdsReject.push_back(reqActionId);
            }
          }
          break;
        }
      default:
        {
          NS_LOG_DEBUG ("in case default");	
          break;
        }      
      }
  }
  
  NS_LOG_DEBUG ("Create RIC Subscription Response");
  
  E2AP_PDU *e2ap_pdu = (E2AP_PDU*)calloc(1,sizeof(E2AP_PDU));

  long *accept_array = &actionIdsAccept[0];
  long *reject_array = &actionIdsReject[0];
  int accept_size = actionIdsAccept.size();
  int reject_size = actionIdsReject.size();

  encoding::generate_e2apv1_subscription_response_success(e2ap_pdu, accept_array, reject_array, accept_size, reject_size, reqRequestorId, reqInstanceId);

  NS_LOG_DEBUG ("Send RIC Subscription Response");
  m_e2sim->encode_and_send_sctp_data(e2ap_pdu);

  RicSubscriptionRequest_rval_s reqParams;
  reqParams.requestorId = reqRequestorId;
  reqParams.instanceId = reqInstanceId;
  reqParams.ranFuncionId = ranFuncionId;
  reqParams.actionId = reqActionId;
  return reqParams;
}

void
E2Termination::SendE2Message (E2AP_PDU* pdu)
{
  m_e2sim->encode_and_send_sctp_data (pdu);
}

}
